export default {
  logo: require('../images/logo.png'),
  camera: require('../images/camera.png'),
  user: require('../images/user.png'),
  mail: require('../images/mail.png'),
  lock: require('../images/lock.png'),
  search: require('../images/search.png'),
  cancel: require('../images/cancel.png'),
  back: require('../images/back.png'),
  hide: require('../images/hide.png'),
  show: require('../images/show.png'),
  edit: require('../images/edit.png'),
  nowifi: require('../images/nowifi.png'),
  success: require('../images/success.png'),
  successright: require('../images/success_right.png'),
};
